# Generated by Django 4.2.30 on 2026-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('entertainment', 'Entertainment'), ('sports', 'Sports'), ('tech', 'Tech')], db_index=True, default='general', max_length=50),
        ),
    ]
